version: '3.8'
services:
  backend:
    build: ./foodplanner-backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./foodplanner-frontend
    volumes:
      - ./foodplanner-frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm start

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: foodplanner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
